import grpc
import argparse
import sys
import time
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.live import Live

# Import files generated by protoc

import DeviceFleetManager_pb2
import DeviceFleetManager_pb2_grpc

console = Console()

# Enums mappings for visualization

DEVICE_STATUS = {0: "IDLE", 1: "BUSY", 2: "OFFLINE", 3: "MAINTENANCE", 4: "UPDATING", 5: "RECOVERING"}
ACTION_STATUS = {0: "[yellow]PENDING[/]", 1: "[bold cyan]RUNNING[/]", 2: "[bold green]COMPLETED[/]", 3: "[bold red]FAILED[/]"}

def get_stub():
    channel = grpc.insecure_channel('localhost:50051')
    return DeviceFleetManager_pb2_grpc.DeviceFleetManagerServiceStub(channel)

def register(args):
    stub = get_stub()
    try:
        response = stub.RegisterDevice(DeviceFleetManager_pb2.DeviceRequest(
            id=args.id, name=args.name, status=args.status
        ))
        console.print(Panel(f"[bold green]Success:[/] {response.message}", title="gRPC RegisterDevice"))
    except Exception as e:
        console.print(f"[bold red]Error:[/] {e}")

def list_devices(args):
    stub = get_stub()
    try:
        response = stub.ListDevices(DeviceFleetManager_pb2.Empty())
        table = Table(title="Device Fleet")
        table.add_column("ID", justify="right", style="cyan")
        table.add_column("Nombre", style="magenta")
        table.add_column("Status", justify="center")

        for dev in response.devices:
            status_text = DEVICE_STATUS.get(dev.status, "UNKNOWN")
            table.add_row(str(dev.id), dev.name, status_text)
        
        console.print(table)
    except Exception as e:
        console.print(f"[bold red]Error:[/] {e}")

def initiate_action(args):
    stub = get_stub()
    try:
        res = stub.InitiateAction(DeviceFleetManager_pb2.ActionRequest(
            device_id=args.id, action_type=args.type, params=args.params
        ))
        action_id = res.action_id
        console.print(f"[bold green]Action started![/] Tracking ID: [bold cyan]{action_id}[/]")
        
        if args.watch:
            watch_action(stub, action_id, args.id)
    except Exception as e:
        console.print(f"[bold red]Error:[/] {e}")

def watch_action(stub, action_id, device_id):
    with Live(console=console, refresh_per_second=2) as live:
        while True:
            act_res = stub.GetActionStatus(DeviceFleetManager_pb2.ActionID(id=action_id))
            dev_res = stub.GetDeviceInfo(DeviceFleetManager_pb2.DeviceID(id=device_id))
            
            status_str = ACTION_STATUS.get(act_res.status, "UNKNOWN")
            dev_str = DEVICE_STATUS.get(dev_res.status, "UNKNOWN")
            
            table = Table(title=f"Monitoring Action #{action_id}")
            table.add_column("Entity")
            table.add_column("Current Status")
            table.add_row("Asynchronous Process", status_str)
            table.add_row("Physical Device", dev_str)
            
            live.update(table)
            
            if act_res.status >= 2: # Completed o Failed

                break
            time.sleep(1)

def main():
    parser = argparse.ArgumentParser(description="Device Fleet Manager TUI Client")
    subparsers = parser.add_subparsers(dest="command")

    # Command: register

    reg_parser = subparsers.add_parser('register', help='Register new device')
    reg_parser.add_argument('--id', type=int, required=True)
    reg_parser.add_argument('--name', type=str, required=True)
    reg_parser.add_argument('--status', type=int, default=0)

    # Command: list

    subparsers.add_parser('list', help='List devices')

    # Command: action

    act_parser = subparsers.add_parser('action', help='Start action on device')
    act_parser.add_argument('--id', type=int, required=True, help="Device ID")
    act_parser.add_argument('--type', type=str, default="SOFTWARE_UPDATE")
    act_parser.add_argument('--params', type=str, default="v1.0")
    act_parser.add_argument('--watch', action='store_true', help="Real time monitoring")

    args = parser.parse_args()

    if args.command == 'register': register(args)
    elif args.command == 'list': list_devices(args)
    elif args.command == 'action': initiate_action(args)
    else: parser.print_help()

if __name__ == '__main__':
    main()